#!/bin/zsh
#
# Script to build the release version of the MIDI Monitor application.

# Display commands as they happen -- useful for debugging
#setopt XTRACE

# build output directory -- change this to whatever you like
BUILD_OUTPUT_DIR=${HOME}/MIDIMonitorBuild

INSTALL_DIRECTORY=${BUILD_OUTPUT_DIR}/PackagedSource

PACKAGED_SOURCE_NAME=MIDI\ Monitor\ Source
PACKAGED_SOURCE_ARCHIVE_NAME=MIDIMonitorSource


#ThisScriptDir=`dirname ${PWD}/$0`

SourceRoot=~/Source
SnoizeSource=${SourceRoot}/Snoize
SnoizeFrameworkSource=${SnoizeSource}/Frameworks
SnoizeAppSource=${SnoizeSource}/Applications
SnoizeScriptSource=${SnoizeSource}/Scripts
SnoizeDocsSource=${SnoizeSource}/Documentation


mkdir -p "$INSTALL_DIRECTORY" || {echo "Couldn't create install directory!"; exit 1}

rm -rf "$INSTALL_DIRECTORY/$PACKAGED_SOURCE_NAME" || {echo "Couldn't remove old packaged source!"; exit 1}

mkdir -p "$INSTALL_DIRECTORY/$PACKAGED_SOURCE_NAME" || {echo "Couldn't create install directory!"; exit 1}

cd $INSTALL_DIRECTORY/$PACKAGED_SOURCE_NAME

mkdir Frameworks; cd Frameworks
cp -R $SnoizeFrameworkSource/SnoizeMIDI .
cp -R $SnoizeFrameworkSource/DisclosableView .
cp -R $SnoizeFrameworkSource/SnoizeMIDISpy .
cd ..

mkdir Applications; cd Applications
cp -R $SnoizeAppSource/MIDIMonitor .
cd ..

mkdir Scripts; cd Scripts
cp -R $SnoizeScriptSource/BuildMIDIMonitor .
cd ..

cp -R $SnoizeDocsSource/MIDIMonitor/Source/README .
cp -R $SnoizeDocsSource/MIDIMonitor/Source/LICENSE .

#
# Remove extra junk from the source
#

find . -type d -name CVS -exec rm -rf {} \; -prune
find . -name \*.mode1 -exec rm {} \;
find . -name \*.pbxuser -exec rm {} \;

#
# Archive it up
#

cd ..
tar -czf ${PACKAGED_SOURCE_ARCHIVE_NAME}.tar.gz $PACKAGED_SOURCE_NAME

echo -n "Done: "
echo ${PWD}/${PACKAGED_SOURCE_ARCHIVE_NAME}.tar.gz
